In [ ]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
print(arr)

for i in arr:
 uniques = np.unique(arr[0])
 uniques1 = np.unique(arr[1])
 uniques2 = np.unique(arr[2])
 uniques3 = np.unique(arr[3])
 uniques4 = np.unique(arr[4])
 uniques5 = np.unique(arr[5])
#valores unicos
print('Linha 1: ',len(uniques))
print('Linha 2: ',len(uniques1))
print('Linha 3: ',len(uniques2))
print('Linha 4: ',len(uniques3))
print('Linha 5: ',len(uniques4))
print('Linha 6: ',len(uniques5))


[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
Linha 1:  7
Linha 2:  7
Linha 3:  5
Linha 4:  7
Linha 5:  7
Linha 6:  8
